name: 'AWS ECR Image Scan action'
description: 'Trigger the scan for the specified docker image in AWS ECR repo and fetch info about the vulnerable packages in the image'
inputs:
  aws_access_key_id:
    description: 'AWS access key id'
    required: true
  aws_secret_access_key:
    description: 'AWS secret access key'
    required: true
  aws_region:
    description: 'AWS region'
    required: true
  aws_account_id:
    description: 'AWS account_id'
    required: true
  aws_ecr_repo:
    description: 'AWS ECR repo name'
    required: true
  aws_ecr_tag:
    description: 'Docker image's tag name. Defaults to latest if not specified'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'